@echo off
echo Checking for process on port 8082...
for /f "tokens=5" %%a in ('netstat -ano 2^>nul ^| findstr ":8082 " ^| findstr "LISTENING"') do (
    echo Killing PID %%a on port 8082...
    taskkill /PID %%a /F >nul 2>&1
)
echo Starting backend...
call mvnw.cmd spring-boot:run
